/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hotel.management.system;

import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class AddItem extends javax.swing.JFrame {

    /** Creates new form AddItem */
    public AddItem() {
        setLocation(300, 100);
        initComponents();
         jPanel2.setBackground(new Color(100,250,204,20));
         item_name.requestFocus();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        GoHome = new javax.swing.JLabel();
        item_price = new javax.swing.JTextField();
        item_name = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        add_item_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));
        jPanel1.setLayout(null);

        GoHome.setBackground(new java.awt.Color(0, 0, 102));
        GoHome.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        GoHome.setForeground(new java.awt.Color(153, 153, 255));
        GoHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/home_50px_1.png"))); // NOI18N
        GoHome.setText("GO HOME");
        GoHome.setOpaque(true);
        GoHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                GoHomeMousePressed(evt);
            }
        });
        jPanel1.add(GoHome);
        GoHome.setBounds(840, 0, 160, 50);

        item_price.setForeground(new java.awt.Color(255, 255, 255));
        item_price.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        item_price.setOpaque(false);
        item_price.setSelectionColor(new java.awt.Color(0, 0, 0));
        item_price.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_priceActionPerformed(evt);
            }
        });
        item_price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                item_priceKeyPressed(evt);
            }
        });
        jPanel1.add(item_price);
        item_price.setBounds(400, 250, 310, 50);

        item_name.setForeground(new java.awt.Color(255, 255, 255));
        item_name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        item_name.setOpaque(false);
        item_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_nameActionPerformed(evt);
            }
        });
        item_name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                item_nameKeyPressed(evt);
            }
        });
        jPanel1.add(item_name);
        item_name.setBounds(400, 170, 310, 50);

        jLabel2.setFont(new java.awt.Font("Tekton Pro Ext", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setText("ITEM NAME");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(210, 190, 180, 32);

        jLabel3.setFont(new java.awt.Font("Tekton Pro Ext", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 255));
        jLabel3.setText("ITEM PRICE");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(210, 270, 170, 32);

        add_item_button.setBackground(new java.awt.Color(0, 0, 0));
        add_item_button.setFont(new java.awt.Font("Tekton Pro Ext", 1, 24)); // NOI18N
        add_item_button.setForeground(new java.awt.Color(153, 153, 255));
        add_item_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/20200910_115344_copy_120x100.png"))); // NOI18N
        add_item_button.setText("ADD ITEM");
        add_item_button.setOpaque(false);
        add_item_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_item_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(483, Short.MAX_VALUE)
                .addComponent(add_item_button)
                .addGap(32, 32, 32))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(356, Short.MAX_VALUE)
                .addComponent(add_item_button, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(90, 80, 790, 470);

        jLabel1.setBackground(new java.awt.Color(0, 0, 102));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/Mainscreensdf_4.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1);
        jLabel1.setBounds(4, 4, 1000, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void add_item_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_item_buttonActionPerformed
        // TODO add your handling code here:
        String itemName,itemPrice;
        itemName=item_name.getText();
        itemPrice = item_price.getText();
        if(itemName.equals("")||itemPrice.equals("")){                          //Checking khali naki
            JOptionPane.showMessageDialog(null, "Please fill the details");
            return;
        }
        int l =itemPrice.length();
        for(int i=0;i<l;i++){                                                   //Checking if price is in invalid format
            if(itemPrice.charAt(i)>'9'||itemPrice.charAt(i)<'0'){
                JOptionPane.showMessageDialog(null, "Invalid price");
                return;
            }
        }
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con;
            con=DriverManager.getConnection("JDBC:mysql://localhost:3306/mysql","root","");
            Statement stmt;
            stmt=con.createStatement();
            stmt.executeUpdate("USE hotelmanagementsystem");                        //Sql statement execute korchi nicher line e insert er jonno
            stmt.executeUpdate("insert into restitem(item_name,item_price) values('"+itemName+"','"+itemPrice+"');");//restitem table e itemName ar itemPrice rakhtesi
            JOptionPane.showMessageDialog(null, "Item Added");                                                      
            new Restmenu().setVisible(true);
            this.setVisible(false);
        }
        catch(Exception e)
        {
            System.out.println("Exception: "+e);
        }
    }//GEN-LAST:event_add_item_buttonActionPerformed

    private void GoHomeMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoHomeMousePressed
        // TODO add your handling code here:
        
        new Restmenu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_GoHomeMousePressed

    private void item_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item_nameActionPerformed

    private void item_priceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_priceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_item_priceActionPerformed

    private void item_priceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_item_priceKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            item_price.requestFocus();
    }//GEN-LAST:event_item_priceKeyPressed

    private void item_nameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_item_nameKeyPressed
        // TODO add your handling code here:
        
         if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            item_price.requestFocus();
    }//GEN-LAST:event_item_nameKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel GoHome;
    private javax.swing.JButton add_item_button;
    private javax.swing.JTextField item_name;
    private javax.swing.JTextField item_price;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

}
