/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.management.system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USER
 */
public class CustomerList extends javax.swing.JFrame {

    /**
     * Creates new form CustomerList
     */
    public CustomerList() {
        setLocation(300, 100);
        initComponents();
        showDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        table.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Customer Name", "Contact", "NID Number", "Room Number", "Inhabitants"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 140, 860, 300);

        jLabel2.setBackground(new java.awt.Color(0, 51, 51));
        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 153, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/home_70px.png"))); // NOI18N
        jLabel2.setText("GO HOME");
        jLabel2.setOpaque(true);
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, 0, 200, 60);

        jLabel3.setBackground(new java.awt.Color(0, 0, 51));
        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 153, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/hotel/management/system/exit_30px.png"))); // NOI18N
        jLabel3.setText("LOGOUT");
        jLabel3.setOpaque(true);
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(840, 0, 160, 50);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Menu/room.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 600);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void showDetails(){
        DefaultTableModel model = (DefaultTableModel)table.getModel();  
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con;
            con=DriverManager.getConnection("JDBC:mysql://localhost:3306/mysql","root","");
            Statement stmt;
            stmt=con.createStatement();
            stmt.executeUpdate("use hotelmanagementsystem;");
            ResultSet rs=stmt.executeQuery("select * from bookings a join customer b where a.NID =b.NID and a.checkout is null;");
            /*
            Jodi Database table duita er NID soman hoy tahole oi row ta select hobe.
            
            JOINs are clauses in SQL statements that link two tables together
            aro jante chaile go to https://launchschool.com/books/sql/read/joins
            
            Upore Bookings ar Customer join kore query korechi.
            */
            
            while(rs.next()){
                String name=rs.getString("name");
                String contact=rs.getString("contact");
                String NID=rs.getString("NID");
                String room=rs.getString("room");
                String number_of_persons = rs.getString("number_of_persons");
                
                model.addRow(new Object[]{name,contact,NID,room,number_of_persons});    //Table e row add kortesi 2 ta Database Table theke data niye
            }
            rs.close();  
            con.close();
            stmt.close();           
        }
        catch(Exception e)
        {
            System.out.println("Esception: "+e);
        }
        table.setModel(model);        
    }    

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        // TODO add your handling code here:
        int row = table.rowAtPoint(evt.getPoint());
        String room = (String) table.getValueAt(row, 3);
        String NID = (String) table.getValueAt(row, 2);
        /*
            ekhane amra table er je row te click korchi sei row er specific data nicchi
            ekhane getValueAt er syntax getValueAt(row, coloumn-1)
        */
        
        /*
            CheckOut er kaj suru ekhane...
        */
        
        Date date = new Date();
        long CheckoutTime = date.getTime();     //Ajker date return kore
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con;
            con=DriverManager.getConnection("JDBC:mysql://localhost:3306/mysql","root","");
            Statement stmt;
            stmt=con.createStatement();
            stmt.executeUpdate("use hotelmanagementsystem;");
            ResultSet rs=stmt.executeQuery("select * from bookings a join customer b where a.NID =b.NID and a.checkout is null and a.NID='"+NID+"';");
            rs.next();                      //Same uporer moto join korechi bookings ar customer database table
            String id = rs.getString("id");
            String amount = rs.getString("amount");
            String checkin = rs.getString("checkin");       //Checkout ar Checkin er modhher time
            long checkinTime = Long.parseLong(checkin);
            long bill = Long.parseLong(amount);
            
            
            rs = stmt.executeQuery("select * from room where id='"+room+"';");    //Room database er id select korbo jeta click kore select kora room
            rs.next();
            int price = Integer.parseInt(rs.getString("price"));                //Room DataBase theke price nibo room er per night
            long division = 1000*60*60*24;
            long days = (CheckoutTime-checkinTime)/division+1;                  //JAVA Date Api theke Time ber korar upay
            bill=bill+price*days;                                      //https://crunchify.com/how-to-calculate-the-difference-between-two-java-date-instances/
            
            int dialogButton = JOptionPane.YES_NO_OPTION;                       //YES_NO_OPTION e Yes==0 && NO==1
            int dialogResult = JOptionPane.showConfirmDialog(this, "Customer Total Bill: "+bill, "Checkout The Selected Customer?", dialogButton);
            
            /*
            Jodi Yes dei tahole:
            1. Room unoccupied hobe room database table e
            2. Oi Room er id e joto book kora food ase sob DELETE hobe bookfood DB e
            3. Bookings DB e checkout time update hobe.
            4. Bookings DB e amount hobe total Bill
            ******/
            
            if(dialogResult == 0) {
                stmt.executeUpdate("update room set occupied=0 where id='"+room+"';");
                stmt.executeUpdate("DELETE from bookfood WHERE room_id ='"+room+"';");
                stmt.executeUpdate("update bookings set checkout='"+CheckoutTime+"' where id='"+id+"';");
                stmt.executeUpdate("update bookings set amount='"+bill+"' where id='"+id+"';");     //id mane room number in DB
                JOptionPane.showMessageDialog(this, "Checked Out");
                new CustomerList().setVisible(true);
                this.setVisible(false);
                con.close();
                stmt.close();          
            } 
            else{
                return; 
            }             
        }
        catch(Exception e)
        {
            System.out.println("Exception: "+e);
        }
        
        
        
    }//GEN-LAST:event_tableMouseClicked

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        // TODO add your handling code here:
        
        new MainScreen().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MousePressed
        // TODO add your handling code here:
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel3MousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerList().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables
}
