/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hotel.management.system;

import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class RemoveItem extends javax.swing.JFrame {

    /**
     * Creates new form RemoveItem
     */
    public RemoveItem() {
        setLocation(300, 100);
        initComponents();
        jPanel2.setBackground(new Color(100,204,204,70));
        item_name.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        item_name = new javax.swing.JTextField();
        Back = new javax.swing.JLabel();
        RemoveItem = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 102));
        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("ITEM NAME");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(200, 150, 150, 80);

        item_name.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(51, 0, 0)));
        item_name.setOpaque(false);
        jPanel1.add(item_name);
        item_name.setBounds(320, 150, 340, 50);

        Back.setBackground(new java.awt.Color(0, 0, 102));
        Back.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Back.setForeground(new java.awt.Color(153, 153, 255));
        Back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/back_50px.png"))); // NOI18N
        Back.setText("GO BACK");
        Back.setOpaque(true);
        Back.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BackMousePressed(evt);
            }
        });
        jPanel1.add(Back);
        Back.setBounds(650, 0, 150, 50);

        RemoveItem.setBackground(new java.awt.Color(153, 0, 0));
        RemoveItem.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        RemoveItem.setForeground(new java.awt.Color(255, 153, 153));
        RemoveItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/remove_50px.png"))); // NOI18N
        RemoveItem.setText("REMOVE ITEM");
        RemoveItem.setOpaque(true);
        RemoveItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                RemoveItemMousePressed(evt);
            }
        });
        jPanel1.add(RemoveItem);
        RemoveItem.setBounds(530, 330, 150, 50);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 340, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(110, 80, 610, 340);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/remove.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 800, 450);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackMousePressed
        // TODO add your handling code here:
        new Restmenu().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BackMousePressed

    private void RemoveItemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RemoveItemMousePressed
        // TODO add your handling code here:
        
        String name;
        name=item_name.getText();
        
        if(name.equals("")){
            JOptionPane.showMessageDialog(null, "Please fill the details");
            return;
        }
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con;
            con=DriverManager.getConnection("JDBC:mysql://localhost:3306/mysql","root","");
            Statement stmt;
            stmt=con.createStatement();
            stmt.executeUpdate("USE hotelmanagementsystem");
            
            ResultSet rs = stmt.executeQuery("select * from restitem;");   //Query kore result amra ResultSet rs e rakhlam
            int flag=0;
            while(rs.next()){                                  //Ekta Ekta Row te query hobe
                String Name = rs.getString("item_name");
                if(name.equals(Name)){                         //Jodi input item name ar database er item name mile jay
                    flag=1;                                    //flag = 1 hobe
                    break;
                }
            }
            if(flag==0) 
                    JOptionPane.showMessageDialog(null, "Food Item not available");
            rs.close();
            if(flag==1){                                                                    //jodi item mile taile remove korbo database table theke.
                stmt.executeUpdate("DELETE from restitem WHERE item_name ='"+name+"';");    //Restaurant menu er table restitem theke input er item delete korechi
                JOptionPane.showMessageDialog(null, "Item Removed");
                new Restmenu().setVisible(true);
                this.setVisible(false);
            }
            else item_name.setText("");
        }
        catch(Exception e)
        {
            System.out.println("Exception: "+e);
        }
    }//GEN-LAST:event_RemoveItemMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoveItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoveItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoveItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoveItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoveItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Back;
    private javax.swing.JLabel RemoveItem;
    private javax.swing.JTextField item_name;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
